apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-finance-business-landing
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-finance-business-landing
      tier: backend
  template:
    metadata:
      labels:
        app: trust-finance-business-landing
        tier: backend
    spec:
      containers:
        - name: trust-finance-business-landing
          image: 662706723018.dkr.ecr.ap-southeast-1.amazonaws.com/trust-finance-business-landing:latest
          imagePullPolicy: Always
          command: ["npm", "run", "start"]
          resources:
            limits:
              cpu: 200m
              memory: 256M
            requests:
              cpu: 100m
              memory: 128M
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
