apiVersion: v1
kind: Service
metadata:
  labels:
    app: trust-finance-business-landing
  name: trust-finance-business-landing
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
  selector:
    app: trust-finance-business-landing
